---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# EGLVgauges

<!-- badges: start -->

<!-- badges: end -->

EGLVgauges aims to grant easy access to EGLV gauge data published at [pegel.eglv.de](https://pegel.eglv.de/).

## Installation

You can install the development version of EGLVgauges with:

``` r
# install.packages("devtools")
devtools::install_github("dimfalk/EGLVgauges")
```

## Basic examples

Just a few quick insights on the use of this package:

```{r example}
library(EGLVgauges)

# fetch all available gauges
gauges <- get_gauges()
gauges

# eventually filter the dataset to the ones you're interested in
gauge <- gauges |> dplyr::filter(id == "10119")
gauge



# fetch water level measurements
meas <- get_measurements(gauge)[[1]]
meas

class(meas)

plot(meas, main = "10119 Adenauerallee", ylab = "Water level [cm]")



# fetch metadata available
get_meta(gauge)
```
